### ISSUE TITLE
path visualization

### ISSUE THREAD

**Issue by simonschmeisser** [JeroenDM/moveit_constrained_planning_examples#1]
Hi Jeroen,

in one of your videos I noticed a fancy path visualization using spheres, was that just a MarkerArray or did you use something else for visualization?

**Comment by JeroenDM** [comment]
Hi Simon! It's a nice feature of [moveit_visual_tools](https://github.com/ros-planning/moveit_visual_tools) called [publishTrajectoryLine](https://github.com/ros-planning/moveit_visual_tools/blob/2620189ebadb3b9fa85edf5ee54fc653f145bf66/include/moveit_visual_tools/moveit_visual_tools.h#L577) (that uses a MarkerArray internally). I found it in the [MoveIt tutorials](https://ros-planning.github.io/moveit_tutorials/doc/move_group_interface/move_group_interface_tutorial.html#visualizing-plans) since one of the more recent updates.
